// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddoneitemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addoneitem() {
    // Test name: Add-one-item
    // Step # | name | target | value
    // 1 | open | https://www.amazon.ca/s?k=eraser&crid=2V1R9O4Q1VBZG&sprefix=eraser%2Caps%2C170&ref=nb_sb_noss_1 | 
    driver.get("https://www.amazon.ca/s?k=eraser&crid=2V1R9O4Q1VBZG&sprefix=eraser%2Caps%2C170&ref=nb_sb_noss_1");
    // 2 | setWindowSize | 1097x816 | 
    driver.manage().window().setSize(new Dimension(1097, 816));
    // 3 | click | xpath=//img[@alt='STAEDTLER Mars Plastic Eraser Pack of 3Plastic Mini, White'] | 
    driver.findElement(By.xpath("//img[@alt=\'STAEDTLER Mars Plastic Eraser Pack of 3Plastic Mini, White\']")).click();
    // 4 | click | id=quantity | 
    driver.findElement(By.id("quantity")).click();
    // 5 | select | id=quantity | label=1
    {
      WebElement dropdown = driver.findElement(By.id("quantity"));
      dropdown.findElement(By.xpath("//option[. = '1']")).click();
    }
    // 6 | verifySelectedValue | id=quantity | 1
    {
      String value = driver.findElement(By.id("quantity")).getAttribute("value");
      assertThat(value, is("1"));
    }
    // 7 | click | id=add-to-cart-button | 
    driver.findElement(By.id("add-to-cart-button")).click();
    // 8 | click | css=#nav-cart-text-container > .nav-line-2 | 
    driver.findElement(By.cssSelector("#nav-cart-text-container > .nav-line-2")).click();
    // 9 | verifyText | id=sc-subtotal-label-activecart |  Subtotal (1 item): 
    assertThat(driver.findElement(By.id("sc-subtotal-label-activecart")).getText(), is(" Subtotal (1 item): "));
    // 10 | click | css=.sc-action-delete .a-color-link | 
    driver.findElement(By.cssSelector(".sc-action-delete .a-color-link")).click();
    // 11 | close |  | 
    driver.close();
  }
}
