// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddShippingAddressCanadianTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addShippingAddressCanadian() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(974, 1087));
    {
      WebElement element = driver.findElement(By.id("nav-link-accountList-nav-line-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("nav-link-accountList-nav-line-1")).click();
    driver.findElement(By.cssSelector(".ya-card-row:nth-child(3) > .ya-card-cell:nth-child(1) .a-color-secondary")).click();
    driver.findElement(By.id("ya-myab-plus-address-icon")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressFullName")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressFullName")).sendKeys("John Doe");
    driver.findElement(By.id("address-ui-widgets-enterAddressPhoneNumber")).sendKeys("111-111-1111");
    driver.findElement(By.id("address-ui-widgets-enterAddressLine1")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressLine1")).sendKeys("University Dr NW");
    driver.findElement(By.id("address-ui-widgets-enterAddressLine2")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressLine2")).sendKeys("2500");
    driver.findElement(By.id("address-ui-widgets-enterAddressCity")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressCity")).sendKeys("Calgary");
    driver.findElement(By.cssSelector("#address-ui-widgets-enterAddressStateOrRegion .a-button-text")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_0")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressPostalCode")).click();
    driver.findElement(By.id("address-ui-widgets-enterAddressPostalCode")).sendKeys("T2N1N4");
    driver.findElement(By.cssSelector(".a-button-input")).click();
    assertThat(driver.findElement(By.id("address-ui-widgets-FullName")).getText(), is("John Doe"));
    assertThat(driver.findElement(By.id("address-ui-widgets-AddressLineOne")).getText(), is("University Dr NW 2500"));
    assertThat(driver.findElement(By.id("address-ui-widgets-CityStatePostalCode")).getText(), is("Calgary, Alberta T2N 1N4"));
    assertThat(driver.findElement(By.id("address-ui-widgets-Country")).getText(), is("Canada"));
    assertThat(driver.findElement(By.id("address-ui-widgets-PhoneNumber")).getText(), is("Phone number: ‪111-111-1111‬"));
    driver.findElement(By.id("ya-myab-address-delete-btn-0")).click();
    driver.findElement(By.cssSelector(".a-button-input")).click();
  }
}
