// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangeCountryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changeCountryAU() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("icp-touch-link-country")).click();
    assertThat(driver.getTitle(), is("Go to website"));
    driver.findElement(By.id("icp-dropdown")).click();
    {
      WebElement element = driver.findElement(By.id("icp-dropdown_0"));
      String attribute = element.getAttribute("data-value");
      vars.put("url", attribute);
    }
    vars.put("urlToOpen", js.executeScript("var x = arguments[0]; return x[\"stringVal\"];", vars.get("parse")));
    driver.get("https://www.amazon.ca/vars.get("urlToOpen").toString()");
    assertThat(driver.getTitle(), is("Amazon.com.au: Shop online for Electronics, Apparel, Toys, Books, DVDs & more"));
    driver.close();
  }
  @Test
  public void changeCountryGB() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("icp-touch-link-country")).click();
    assertThat(driver.getTitle(), is("Go to website"));
    driver.findElement(By.id("icp-dropdown")).click();
    {
      WebElement element = driver.findElement(By.id("icp-dropdown_20"));
      String attribute = element.getAttribute("data-value");
      vars.put("url", attribute);
    }
    vars.put("urlToOpen", js.executeScript("var x = arguments[0]; return x[\"stringVal\"];", vars.get("parse")));
    driver.get("https://www.amazon.ca/vars.get("urlToOpen").toString()");
    assertThat(driver.getTitle(), is("Amazon.co.uk: Low Prices in Electronics, Books, Sports Equipment & more"));
    driver.close();
  }
  @Test
  public void changeCountryJP() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("icp-touch-link-country")).click();
    assertThat(driver.getTitle(), is("Go to website"));
    driver.findElement(By.id("icp-dropdown")).click();
    {
      WebElement element = driver.findElement(By.id("icp-dropdown_10"));
      String attribute = element.getAttribute("data-value");
      vars.put("url", attribute);
    }
    vars.put("urlToOpen", js.executeScript("var x = arguments[0]; return x[\"stringVal\"];", vars.get("parse")));
    driver.get("https://www.amazon.ca/vars.get("urlToOpen").toString()");
    assertThat(driver.getTitle(), is("Amazon.co.jp | Books, Apparel, Electronics, Groceries & more"));
    driver.close();
  }
  @Test
  public void changeCountryUS() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("icp-touch-link-country")).click();
    assertThat(driver.getTitle(), is("Go to website"));
    driver.findElement(By.id("icp-dropdown")).click();
    {
      WebElement element = driver.findElement(By.id("icp-dropdown_21"));
      String attribute = element.getAttribute("data-value");
      vars.put("url", attribute);
    }
    vars.put("urlToOpen", js.executeScript("var x = arguments[0]; return x[\"stringVal\"];", vars.get("parse")));
    driver.get("https://www.amazon.ca/vars.get("urlToOpen").toString()");
    assertThat(driver.getTitle(), is("Amazon.com. Spend less. Smile more."));
    driver.close();
  }
}
