// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("twotabsearchtextbox")).click();
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys("towel");
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//a[@class=\'a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal\']/span[contains(text(), \'Towel\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("add-to-cart-button"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("add-to-cart-button")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(text(), \'Go to cart\')]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//a[contains(text(), \'Go to cart\')]")).click();
  }
  @Test
  public void editCart5Items() {
    driver.get("https://www.amazon.ca/gp/cart/view.html?ref_=nav_cart");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("a-autoid-1-announce")).click();
    driver.findElement(By.id("quantity_5")).click();
    {
      String value = driver.findElement(By.id("quantity")).getAttribute("value");
      assertThat(value, is("5"));
    }
  }
  @Test
  public void editCart3Items() {
    driver.get("https://www.amazon.ca/gp/cart/view.html?ref_=nav_cart");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("a-autoid-1-announce")).click();
    driver.findElement(By.id("quantity_3")).click();
    {
      String value = driver.findElement(By.id("quantity")).getAttribute("value");
      assertThat(value, is("3"));
    }
  }
  @Test
  public void deleteItemFromCart() {
    driver.get("https://www.amazon.ca/gp/cart/view.html?ref_=nav_cart");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.id("a-autoid-1-announce")).click();
    driver.findElement(By.id("quantity_0")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".a-padding-medium:nth-child(1) > .a-size-base"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
}
