// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginInvalidEmailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginInvalidEmail() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1174, 696));
    {
      WebElement element = driver.findElement(By.id("nav-logo-sprites"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("nav-hamburger-menu")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".hmenu > li:nth-child(2) > .hmenu-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("b")).click();
    driver.findElement(By.id("ap_email")).click();
    driver.findElement(By.id("ap_email")).sendKeys("notarealemail");
    driver.findElement(By.id("authportal-main-section")).click();
    driver.findElement(By.cssSelector(".a-button-inner > #continue")).click();
    driver.findElement(By.cssSelector("#auth-error-message-box > .a-box-inner")).click();
    driver.findElement(By.cssSelector("#auth-error-message-box > .a-box-inner")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".a-alert-heading"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".a-list-item"));
      assert(elements.size() > 0);
    }
  }
}
